target-version = "py311"
line-length = 100
exclude = [
  ".git",
  ".venv",
  "build",
  "dist",
  "experimental",
  "motherload_projet/.npm-cache",
  "motherload_projet/client",
  "motherload_projet/client/.npm-cache",
  "motherload_projet/client/dist",
  "motherload_projet/client/node_modules",
]

[lint]
select = ["E9", "F63", "F7", "F82"]
